### ISSUE TITLE
Inclusão de Relatorio no Readme.md

### ISSUE THREAD

**Issue by alsantosad** [NewKanvas/M5-Projeto-5#4]
1- Incluir esse texto após REQUISITOS.
Os Dados foram importados do Kaggle

Carregamos e tratados através do Python pelo notebook.

Selecionamos as 10 Maiores moedas e exportamos os dados na pasta Data.

Com o executavel index.py, enviamos os Dados para a pasta do XAMPP.

Para facilitar a importação no MySQL pela query.sql.

Com os Dados tratados decidimos utilizar a ferramenta de visualizacao TABLEAU.

2-  Incluir link com o Relatório Detalhado.

**Comment by NewKanvas** [comment]
Adicionei porém alterei o formato para se adequar ao README
